# Generated by Django 5.2 on 2025-10-05 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_fichier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='fichier',
        ),
    ]
