# Generated by Django 5.2 on 2025-10-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse Email')),
                ('sujet', models.CharField(max_length=200, verbose_name='Sujet du message')),
                ('message', models.TextField(verbose_name='Contenu du message')),
                ('date_envoi', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
                ('traite', models.BooleanField(default=False, verbose_name="Traité (par l'administrateur)")),
            ],
            options={
                'verbose_name': 'Message de Contact',
                'verbose_name_plural': 'Messages de Contact',
                'ordering': ['-date_envoi'],
            },
        ),
    ]
